### ISSUE TITLE
Websocket does not reconnect if initial connect fails

### ISSUE THREAD

**Issue by someguy4321** [Coinigy/PureSocketCluster#10]
I am using your library (from nuget) to connect to a socketcluster server.
If the server is not available when connect is called on the client then the client will never try to reconnect.

If connect is called again it throws an error which seems to be coming from the .Net websocket class complaining about the socket already being started.

The net effect of this is that if the initial connect fails, then the class needs to be disposed and a new one created in order to try to connect again.

My expectations were that the client would continue to try to reconnect even if the server was not available when connect is first called.

I will try and get some logs for you to verify.

Thanks for your hard work.

**Comment by ByronAP** [comment]
Thank you I will investigate further.

NOTE FOR COINIGY USERS: "The websocket API is currently disabled due to excessive load being placed on the platform by people using the API improperly in order to bypass channel-limit restrictions. We've been forced to temporarily suspend the service until we're able to implement a way to prevent people from abusing it and causing issues with the platform. We expect it to be back online within the next couple of weeks." Rob
